version: "3.8"

services:
  web:
    image: djohnson24/web
    command: gunicorn -b 0.0.0.0:8000 -t 120 -w 4 wsgi:app
    ports:
      - 8000:8000
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    env_file:
      - ".env.prod"
    depends_on: 
      - "redis"
      - "db"
    volumes:
      - static_assets:/home/myuser/api/static
  
  worker:
    image: djohnson24/worker
    env_file: 
      - ".env.prod"
      
  db:
    env_file:
      - ".env.prod"

  redis:
    env_file:
      - ".env.prod"

  proxy:
    build:
      context: './deployment/nginx'
      args:
        - project_conf=${DOCKER_PROXY_CONF:-market_basket_app_docker.conf}
    image: djohnson24/proxy
    env_file:
      - ".env.prod"
    ports:
      - 80:80
      - 443:443
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    command: nginx -g "daemon off;"
    volumes:
      - static_assets:/app/static
    depends_on: 
      - "web"
  
  
volumes:
  static_assets:


  