version: "3.8"

services:
  web:
    build:
      context: "."
    command: gunicorn -b 0.0.0.0:8000 -t 120 -w 4 wsgi:app
    ports: 
      - 8000:8000
    env_file:
      - ".env"
    depends_on: 
      - "redis"


  